import type {
  ClaimRecord,
  OrganisationSettings,
  ReceiptRecord,
  ReconciliationLine,
  SessionState,
  SupplierRule,
} from "./types";

export const demoSession: SessionState = {
  token: "demo-token",
  user: {
    id: 14,
    organisationId: 101,
    email: "finance@exdox.co.uk",
    fullName: "Alex Rowe",
    role: "Business_Admin",
    status: "active",
  },
  organisations: [{ id: 101, name: "Exdox Advisory Ltd" }],
  activeOrganisationId: 101,
  allowedWebRoutes: ["/overview", "/costs", "/sales", "/claims", "/rules", "/reconciliation", "/settings", "/requisitions", "/bank-callback"],
};

export const demoReceipts: ReceiptRecord[] = [
  {
    id: 501,
    organisationId: 101,
    workspaceContext: "cost",
    paymentMethod: "business_card",
    claimId: null,
    status: "Review",
    category: "Software",
    receiptSource: "mobile",
    sourceFilename: "aws-renewal-june.pdf",
    sourceMimeType: "application/pdf",
    s3Bucket: "exdox-demo",
    s3Key: "receipts/org-101/cost/aws-renewal-june.pdf",
    vendorName: "Amazon Web Services",
    invoiceDate: "2026-07-02",
    dueDate: "2026-07-12",
    invoiceNumber: "AWS-77841",
    currency: "GBP",
    totalAmount: 412.5,
    netAmount: 343.75,
    vatAmount: 68.75,
    taxRateApplied: "20% Standard",
    needsReview: true,
    rawTextSummary: "Monthly AWS hosting and storage charges.",
    createdAt: "2026-07-02T09:15:00.000Z",
    updatedAt: "2026-07-08T10:30:00.000Z",
  },
  {
    id: 502,
    organisationId: 101,
    workspaceContext: "cost",
    paymentMethod: "cash_personal",
    claimId: 9002,
    status: "Ready",
    category: "Travel",
    receiptSource: "email",
    sourceFilename: "rail-london-manchester.pdf",
    sourceMimeType: "application/pdf",
    s3Bucket: "exdox-demo",
    s3Key: "receipts/org-101/cost/rail-london-manchester.pdf",
    vendorName: "Avanti West Coast",
    invoiceDate: "2026-07-03",
    dueDate: null,
    invoiceNumber: "TRN-1513",
    currency: "GBP",
    totalAmount: 148,
    netAmount: 123.33,
    vatAmount: 24.67,
    taxRateApplied: "20% Standard",
    needsReview: false,
    rawTextSummary: "Return rail travel for client visit.",
    createdAt: "2026-07-03T12:00:00.000Z",
    updatedAt: "2026-07-08T08:00:00.000Z",
  },
  {
    id: 504,
    organisationId: 101,
    workspaceContext: "cost",
    paymentMethod: "cash_personal",
    claimId: 9001,
    status: "Review",
    category: "Travel",
    receiptSource: "mobile",
    sourceFilename: "hotel-bristol-summit.pdf",
    sourceMimeType: "application/pdf",
    s3Bucket: "exdox-demo",
    s3Key: "receipts/org-101/cost/hotel-bristol-summit.pdf",
    vendorName: "Harbour Hotel Bristol",
    invoiceDate: "2026-06-29",
    dueDate: null,
    invoiceNumber: "HTL-2209",
    currency: "GBP",
    totalAmount: 320.1,
    netAmount: 266.75,
    vatAmount: 53.35,
    taxRateApplied: "20% Standard",
    needsReview: true,
    rawTextSummary: "Two-night stay for Q2 client workshop roadshow.",
    createdAt: "2026-06-29T18:20:00.000Z",
    updatedAt: "2026-07-07T09:45:00.000Z",
  },
  {
    id: 505,
    organisationId: 101,
    workspaceContext: "cost",
    paymentMethod: "cash_personal",
    claimId: 9001,
    status: "Ready",
    category: "Meals",
    receiptSource: "email",
    sourceFilename: "client-dinner-bristol.pdf",
    sourceMimeType: "application/pdf",
    s3Bucket: "exdox-demo",
    s3Key: "receipts/org-101/cost/client-dinner-bristol.pdf",
    vendorName: "Box-E Bristol",
    invoiceDate: "2026-06-30",
    dueDate: null,
    invoiceNumber: "DIN-8841",
    currency: "GBP",
    totalAmount: 322.1,
    netAmount: 268.42,
    vatAmount: 53.68,
    taxRateApplied: "20% Standard",
    needsReview: false,
    rawTextSummary: "Team dinner with client after workshop delivery.",
    createdAt: "2026-06-30T21:05:00.000Z",
    updatedAt: "2026-07-07T10:10:00.000Z",
  },
  {
    id: 503,
    organisationId: 101,
    workspaceContext: "sales",
    paymentMethod: "bank_transfer",
    claimId: null,
    status: "Published",
    category: "Consulting Revenue",
    receiptSource: "web_upload",
    sourceFilename: "client-invoice-4478.pdf",
    sourceMimeType: "application/pdf",
    s3Bucket: "exdox-demo",
    s3Key: "receipts/org-101/sales/client-invoice-4478.pdf",
    vendorName: "Harbour & Finch LLP",
    invoiceDate: "2026-07-04",
    dueDate: "2026-08-03",
    invoiceNumber: "EX-4478",
    currency: "GBP",
    totalAmount: 2400,
    netAmount: 2000,
    vatAmount: 400,
    taxRateApplied: "20% Standard",
    needsReview: false,
    rawTextSummary: "Monthly finance transformation retainer.",
    createdAt: "2026-07-04T09:00:00.000Z",
    updatedAt: "2026-07-07T15:00:00.000Z",
  },
];

export const demoClaims: ClaimRecord[] = [
  {
    id: 9001,
    name: "Q2 Sales Travel",
    description: "Field visits and client meals",
    currency: "GBP",
    status: "pending",
    totalAmount: 642.2,
    documentCount: 2,
    createdAt: "2026-07-01T10:00:00.000Z",
    updatedAt: "2026-07-07T14:00:00.000Z",
    createdByUserId: 22,
    organisationId: 101,
  },
  {
    id: 9002,
    name: "June Client Workshops",
    description: "Transport and subsistence",
    currency: "GBP",
    status: "approved",
    totalAmount: 148,
    documentCount: 1,
    createdAt: "2026-06-28T10:00:00.000Z",
    updatedAt: "2026-07-06T14:00:00.000Z",
    createdByUserId: 19,
    organisationId: 101,
  },
];

export const demoRules: SupplierRule[] = [
  {
    id: 1,
    supplierMatchText: "amazon web services",
    category: "Software",
    taxRate: "20% Standard",
    paymentMethod: "business_card",
    isActive: true,
  },
  {
    id: 2,
    supplierMatchText: "avanti",
    category: "Travel",
    taxRate: "20% Standard",
    paymentMethod: "cash_personal",
    isActive: true,
  },
];

export const demoReconciliation: ReconciliationLine[] = [
  {
    id: 81,
    transactionId: "txn_aws_0703",
    bookingDate: "2026-07-03",
    remittanceInformation: "AWS EMEA AWS AMAZON.CO.UK",
    transactionAmount: 412.5,
    statementDate: "2026-07-03",
    description: "AWS EMEA AWS AMAZON.CO.UK",
    amountSpent: 412.5,
    status: "Open",
    matchedReceiptId: null,
    candidates: [
      {
        id: 501,
        vendorName: "Amazon Web Services",
        invoiceDate: "2026-07-02",
        totalAmount: 412.5,
        status: "Review",
        category: "Software",
        receiptSource: "mobile",
        matchScore: 0.92,
      },
    ],
  },
  {
    id: 82,
    transactionId: "txn_avanti_0703",
    bookingDate: "2026-07-03",
    remittanceInformation: "AVANTI WEST COAST",
    transactionAmount: 148,
    statementDate: "2026-07-03",
    description: "AVANTI WEST COAST",
    amountSpent: 148,
    status: "Audited",
    matchedReceiptId: 502,
    candidates: [
      {
        id: 502,
        vendorName: "Avanti West Coast",
        invoiceDate: "2026-07-03",
        totalAmount: 148,
        status: "Ready",
        category: "Travel",
        receiptSource: "email",
        matchScore: 1,
      },
    ],
  },
];

export const demoSettings: OrganisationSettings = {
  organisationId: 101,
  organisationName: "Exdox Advisory Ltd",
  isVatRegistered: true,
  defaultTaxRate: "20% Standard",
};
